artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/llm_model_01.h5
  updated_base_model_path: artifacts/base_model/base_llm_model_update.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5